export { default as DegenMobileLayout } from './DegenMobileLayout.js'
export { default as Header } from './Header.js'
export { default as Footer } from './Footer.js'
export { default as MainContent } from './MainContent.js'
export { default as BottomNavigation } from './BottomNavigation.js'
export { default as Game } from './Game.js'
export { degenMobileTheme } from './theme.js'