export { default as DegenMobileLayout } from './DegenMobileLayout'
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as MainContent } from './MainContent'
export { default as BottomNavigation } from './BottomNavigation'
export { default as Game } from './Game'
export { default as Dashboard } from './Dashboard'
export { degenMobileTheme } from './theme'