import type { GameBundle } from './types'
import React from 'react'

export const ALL_GAMES: GameBundle[] = [
  {
    id: 'scissors',
    live: 'down',
    meta: {
      background: '#000000CC',
      name: 'Scissors',
      image: '/games/scissors/scissors.png',
      description: `Rock, Paper, Scissors - the eternal triangle of choice. Your weapon against fate's computer. Rock crushes dreams, Paper covers truth, Scissors cut through hope. Choose your poison and let the ancient ritual decide your fortune.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Scissors')),
  },
  {
    id: 'dice',
    live: 'up',
    meta: {
      background: '#000000CC',
      name: 'Dice',
      image: '/games/dice/dice.png',
      description: `Whisper your number to fate and let the dice fall like rain on your secrets. The higher you climb, the gentler the fall. A slider for your sins and a payout for your prayers. Every roll is a quiet confession.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Dice')),
  },
  {
    id: 'slots',
    live: 'up',
    meta: {
      background: '#000000CC',
      name: 'Slots',
      image: '/games/slots/slots.png',
      description: `Spin me slowly, darling. Five reels dance in a symphony of risk and rhythm. Common loves, rare obsessions, and legendary heartbreaks line up like old memories. When they align, you'll feel it. Payout poetry in motion.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Slots')),
  },
  {
    id: 'flip',
    live: 'up',
    meta: {
      name: 'Flip',
      image: '/games/flip/flip.png',
      background: '#000000CC',
      description: `Heads or Tails, like love or loss. A perfect 50/50 with no strategy and no mercy. Just raw instinct. Fast. Final. Fatal. The coin spins and you hold your breath like it's the last kiss before goodbye.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Flip')),
  },
  {
    id: 'hilo',
    live: 'up',
    meta: {
      name: 'HiLo',
      image: '/games/hilo/hilo.png',
      background: '#000000CC',
      description: `Lovers lie. Cards don't. Will the next one be higher or will your streak end like all good romances? One right guess leads to another until it doesn't. Know when to hold. Know when to run. Know when enough is enough.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./HiLo')),
  },
  {
    id: 'mines',
    live: 'up',
    meta: {
      name: 'Mines',
      image: '/games/mines/mines.png',
      background: '#000000CC',
      description: `Twenty-five steps in a field of danger. Every click could be your last or your legacy. Choose how deep to dig and how brave to be. Multiply your winnings or vanish with one wrong move. She's a dangerous game but aren't they all?`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Mines')),
  },
  {
    id: 'roulette',
    live: 'up',
    meta: {
      name: 'Roulette',
      image: '/games/roulette/roulette.png',
      background: '#000000CC',
      description: `Spin the wheel of fate and place your heart where logic won't follow. Red or black. Even or odd. This is old money romance. European elegance with pocketed chaos. Let the spin sing your fortune.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Roulette')),
  },
  {
    id: 'plinko',
    live: 'up',
    meta: {
      background: '#000000CC',
      image: '/games/plinko/plinko.png',
      name: 'Plinko',
      description: `Bounce with me. Each drop is a poem of physics and fate. The edge is wild and the center is safe. Choose your thrill. One ball or a hundred, the fall is always beautiful.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Plinko')),
  },
  {
    id: 'crash',
    live: 'up',
    meta: {
      background: '#000000CC',
      image: '/games/crash/crash.png',
      name: 'Crash',
      description: `Launch the rocket and ride the rise but bail before it breaks your heart. It climbs fast and feels eternal. But everything crashes. Set your line. Pray. Then watch the sky burn.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./CrashGame')),
  },
  {
    id: 'blackjack',
    live: 'up',
    meta: {
      background: '#000000CC',
      image: '/games/blackjack/blackjack.png',
      name: 'BlackJack',
      description: `Twenty-one or nothing, baby. This is a game of inches and instincts. You and the dealer in a quiet war for dominance. Hit. Stand. Bluff with your eyes. Get close. Get lucky. Or get busted.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./BlackJack')),
  },
  {
    id: 'crypto-chart',
    live: 'up',
    meta: {
      background: '#000000CC',
      image: '/games/chart/logo.png',
      name: 'Sol Crash',
      description: `Trade emotion, not just numbers. Candles rise like hope and crash like confessions. Watch the chart like you watch your lovers. Closely. Cautiously. You know the risks. You know the thrill.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./CryptoChartGame')),
  },
  {
    id: 'double-or-nothing',
    live: 'up',
    meta: {
      name: 'Double or Nothing',
      image: '/games/doubleornothing/double-or-nothing.png',
      background: '#000000CC',
      description: `This is the coin flip at the altar. No buildup and no buffer. Just pure 50/50. All in or all gone. You don't play this game. This game plays you.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./DoubleOrNothing')),
  },
  {
    id: 'keno',
    live: 'up',
    meta: {
      name: 'Keno',
      image: '/games/keno/keno.png',
      background: '#000000CC',
      description: `Pick numbers like you're picking stars from the sky. Will they align? Will they love you back? Fewer for safety. More for madness. The lottery is a lover with long odds and unforgettable nights.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Keno')),
  },
  {
    id: 'limbo',
    live: 'up',
    meta: {
      name: 'Limbo',
      image: '/games/limbo/limbo.png',
      background: '#000000CC',
      description: `Set your multiplier and hold your breath. The lower the odds, the sweeter the kiss. It's a balancing act between greed and grace. Sometimes you soar. Sometimes you fall into limbo.`,
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Limbo')),
  },
  {
    id: 'diceroll',
    live: 'up',
    meta: {
      name: 'Dice Roll',
      image: '/games/diceroll/dice-roll.png',
      background: '#000000CC',
      description: 'Pure. Classic. A single die and six outcomes. Choose one and pray to whatever gods still listen. One in six, but it feels like one in a million when it hits. Old school love. Sharp and quick.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./DiceRoll')),
  },
  {
    id: 'wheelspin',
    live: 'up',
    meta: {
      name: 'Wheel Spin',
      image: '/games/wheelspin/wheel-spin.png',
      background: '#000000CC',
      description: 'Colorful temptations spinning like carnival dreams. One segment hides the jackpot. The rest are lessons in humility. It\'s flashy. It\'s fun. It\'s fleeting. Like most good things.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./WheelSpin')),
  },
  {
    id: 'luckynumber',
    live: 'up',
    meta: {
      name: 'Lucky Number',
      image: '/games/luckynumber/lucky-number.png',
      background: '#000000CC',
      description: 'One in ten. Ten in one. You\'ve got a lucky number, don\'t you? Trust it. Or doubt it. Either way, you\'re chasing that 10x like it\'s destiny. No rules. Just vibes.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./LuckyNumber')),
  },
  {
    id: 'slide',
    live: 'up',
    meta: {
      name: 'Slide',
      image: '/games/slide/slide.png',
      background: '#000000CC',
      description: 'A slow and sensual slide into chance. Pick a position, low or high. Then hold still as destiny glides to a stop. If it lands just right, it\'s a smooth ride to glory.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./Slide')),
  },
  {
    id: 'progressive-poker',
    live: 'up',
    meta: {
      name: 'Progressive Poker',
      image: '/games/progressive-poker/progressive-poker.png',
      background: '#c9453b',
      description: 'A high-stakes poker variant with a progressive jackpot. Play for the big win as the pot grows with every hand. Classic rules, modern thrill.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./ProgressivePoker/index')),
  },
  {
    id: 'fancy-horse-racing',
    live: 'up',
    meta: {
      name: 'Horse Racing',
      image: '/games/fancy-horse-racing/horse-racing.png',
      background: '#000000CC',
      description: 'Pick your steed and place your bet. Then watch as digital thunder rolls across the screen. Hooves pound and hearts race. You\'re not just betting on a horse. You\'re betting on a heartbeat.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./FancyVirtualHorseRacing')),
  },
  {
    id: 'alien-artifact-hunt',
    live: 'new',
    meta: {
      name: 'Alien Artifact Hunt',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Explore mysterious alien worlds in search of ancient artifacts. Navigate through Earth-like planets, gas giants, and crystal worlds. Each discovery could unlock cosmic treasures or reveal deadly traps.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./AlienArtifactHunt')),
  },
  {
    id: 'deep-sea-dive',
    live: 'new',
    meta: {
      name: 'Deep Sea Dive',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Plunge into the mysterious depths of the ocean to discover hidden treasures. The deeper you dive, the greater the risks and rewards that await in the abyssal darkness.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./DeepSeaDive')),
  },
  {
    id: 'dragon-vault',
    live: 'new',
    meta: {
      name: 'Dragon Vault',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Enter the legendary dragon\'s lair where ancient treasures are guarded by fierce beasts. Only the bravest adventurers dare to claim the hoard\'s most precious gems.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./DragonVault')),
  },
  {
    id: 'galactic-salvage',
    live: 'new',
    meta: {
      name: 'Galactic Salvage',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Scavenge through derelict spaceships and abandoned space stations across the galaxy. Every piece of salvage could be valuable cargo or dangerous alien technology.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./GalacticSalvage')),
  },
  {
    id: 'mystic-crystal-cave',
    live: 'new',
    meta: {
      name: 'Mystic Crystal Cave',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Venture into enchanted crystal caverns where magical gems hold incredible power. Navigate through glowing passages to uncover the cave\'s mystical secrets.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./MysticCrystalCave')),
  },
  {
    id: 'neon-cyber-hack',
    live: 'new',
    meta: {
      name: 'Neon Cyber Hack',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Jack into the neon-lit cyberpunk world where data is currency and hacking is an art form. Breach security systems and steal digital fortunes in this high-tech heist.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./NeonCyberHack')),
  },
  {
    id: 'pirates-fortune',
    live: 'new',
    meta: {
      name: 'Pirates Fortune',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Set sail on the high seas in search of buried treasure and legendary pirate gold. Navigate treacherous waters and battle rival crews for the ultimate maritime fortune.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./PiratesFortune')),
  },
  {
    id: 'pyramid-quest',
    live: 'new',
    meta: {
      name: 'Pyramid Quest',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Explore ancient Egyptian pyramids filled with pharaoh\'s gold and mystical artifacts. Solve ancient puzzles and avoid deadly traps to claim the treasures of the ancients.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./PyramidQuest')),
  },
  {
    id: 'quantum-lab',
    live: 'new',
    meta: {
      name: 'Quantum Lab',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Enter a cutting-edge quantum physics laboratory where reality bends to your will. Manipulate quantum particles and harness the power of probability for incredible rewards.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./QuantumLab')),
  },
  {
    id: 'time-travel-heist',
    live: 'new',
    meta: {
      name: 'Time Travel Heist',
      image: '/games/newgame/coming-soon.jpg',
      background: '#000000CC',
      description: 'Journey through time to pull off the ultimate heist across different eras. From medieval castles to futuristic cities, steal treasures from across the timeline.',
      effect: 'pulse',
    },
    app: React.lazy(() => import('./TimeTravelHeist')),
  },
]
